# -*- coding: utf-8 -*-
"""Quantitativos de Dados em certas colunas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SkuZHVyj2EoBDSQsLyq2eNaWL2kd6Kup

Contar dados em coluna especifica
"""

# Importações:

import pandas as pd
from google.colab import files

# Selecionar Excel:

uploaded = files.upload()

# Data Frame:

# Supondo que o nome do arquivo seja 'dados.xlsx'
#file_name = 'dados.xlsx'
file_name = '13831 Maio 2024.xlsx'

# Carregar o arquivo Excel em um DataFrame
#df = pd.read_excel(file_name)

# Carregar a aba específica ('Planilha1' neste exemplo)
df = pd.read_excel(file_name, sheet_name='Pré-Faturamento', header=9)

linhas = len(df)

print(df.columns)
print(df)
print(f'Número de linhas: {linhas}')

#Filtrando planilha:

df_filtrada = df[['Instalação','Valor Mensal Pró-Rata Item']]

df_filtrada

valor01=df_filtrada.loc[df_filtrada['Valor Mensal Pró-Rata Item'] == 17.3093]
print(f"Quantidade de ocorrencias com valores R$ 17.3093 em 27/05/2024 = {len(valor01)}")

valor02=df_filtrada.loc[df_filtrada['Valor Mensal Pró-Rata Item'] == 8.6547]
print(f"Quantidade de ocorrencias com valores R$ 8.6547 em 29/05/2024 = {len(valor02)}")

total01 = len(valor01)*17.3093
total02 = len(valor02)*8.6547

print(f"Total Valor 01 = R${total01}")
print(f"Total Valor 02 = R${total02}")

total_fatura = total01 + total02

print(f"Total fatura = R${total_fatura:.2f}")