# -*- coding: utf-8 -*-
"""Trabalho Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OFG_NUDDJIPlm3MYVbuLzIkoNtthOpHv

# Acesso aos dados
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/leonhgomes/Pandas/main/pokemon_data.csv')

#Acessando o nome das colunas e o inicio e fim da tabela
print ( df.columns )
print(df.head(3))
print (df.tail(2))



#Acessar colunas individuais
#df['Nome']
df[['Nome','Tipo 1']][0:150:2]

#acessando linhas individuais
df.iloc[:4]

#acessando linhas e colunas individuais
df.iloc[2,1]

#busca por nome
df.loc[df['Tipo 1'] == 'Fogo' ]

#acessar linhas por nome

for indice, linha in df.iterrows() :
  print(indice,linha['Nome'])
  if linha['#'] == 150 :
    break

#valores estatísticos básicos
df.describe()

"""# Ordenação"""

#ordem alfabética inversa
df.sort_values('Nome',ascending=False)

"""# Realizando Mudanças nos dados"""

df['Total'] = df['Ataque'] + df['Atq Esp'] + df['Def Esp'] + df['Defensa'] +df['Velocidade'] + df['Vida']
df

df = df.drop(columns=['Total'])
df

#forma alternativa de criar coluna Total
df['Total'] = df.iloc[:,4:10].sum(axis=1)
df

#renomeando
df.rename({'Defensa':'Defesa'},axis=1,inplace=True)
df

#reordenar colunas

#df = df[ ['Total','Vida','Defesa']    ]

cols = list(df.columns.values )
df = df [cols[0:4] + [cols[-1]] + cols[4:12]]
df

"""#Salvar Arquivos"""

#df.to_csv('modificado.csv')
df.to_csv('modificado.csv',index=False)

#df.to_csv('modificado.txt',index=False,sep='\t')

#df.to_excel('modificado.xlsx',index=False)

"""#Filtrando dados"""

#fogo E agua
novo_df = df.loc[(df['Tipo 1'] =='Fogo') & (df['Tipo 2'] == 'Agua') ]
novo_df

#fogo OU agua
novo_df = df.loc[(df['Tipo 1'] =='Fogo') | (df['Tipo 1'] == 'Agua') ]
novo_df.reset_index(drop=True,inplace=True)
novo_df

#filtrando versões Mega
novo_df = df.loc[~df['Nome'].str.contains('Mega ')]
novo_df

#expressão para pokemons de agua ou fogo
import re

novo_df = df.loc[df['Tipo 1'].str.contains('fogo|agua',flags=re.I,regex=True)]
novo_df

#filtrando pokemons que comecem com PI
novo_df = df.loc[df['Nome'].str.contains('^pi',flags=re.I,regex=True)]
novo_df

"""#Mudanças condicionais"""

df.loc[df['Tipo 1'] == 'Fogo', 'Tipo 1'] = 'Fogueteiro'
df

df.loc[df['Total'] >500, 'Lendario'] = True
df

df.loc[df['Velocidade'] > 70, ['Lendario','Geracao']] = ['Teste1','Teste2']
df

"""#Estatisticas agrupadas (Groupby)"""

df = pd.read_csv('modificado.csv')
df

df.groupby(['Tipo 1']).mean().sort_values('Ataque',ascending=False)

df['contador']=1

df.groupby(['Tipo 1','Tipo 2']).count()['contador']

"""#Blocos de memória"""

#carregar linhas de 5 em 5
for df in pd.read_csv('modificado.csv',chunksize=5) :
  print(df)

"""# Plotagem de dados"""

#histograma

import matplotlib.pyplot as plt


atributo='Defesa'

bins = range(0,201,20)
plt.xticks(bins)

df = pd.read_csv('modificado.csv')

plt.title('Distribuição dos pokemons por ' + atributo)
plt.xlabel('Valor do atributo ' + atributo)
plt.ylabel('Quantidade de pokemons')
plt.hist(df[atributo],bins=bins)
plt.show()

#barra vertical

atributo='Defesa'
tipos = df.groupby('Tipo 1').mean().sort_values(atributo,ascending=False)
linha = tipos.index.tolist()
coluna = tipos[atributo].tolist()
figura = plt.figure(figsize=(14,4)).add_axes([0,0,1,1])
figura.bar(linha,coluna)


plt.xlabel('Tipos de pokemons')
plt.ylabel('Valor médio do atributo ' +atributo)
plt.title('Valor médio do atributo ' + atributo + 'por tipo de pokemons')


for i,v in enumerate(coluna) :
  plt.annotate( f"{v:.2f}",(i-0.3,v+1) )



plt.show()

"""# Exemplo"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/leonhgomes/Pandas/main/pokemon_data.csv')

df.sample(n=6)[ ['Nome','Ataque']  ]